# Closing Reports For mangement

In [68]:
import pandas as pd
import datetime
import time
# pd.options.display.float_format = '{:,.2f}'.format

""" Finding the Last Month """

now = datetime.datetime.now()
last_month = now.month
if now.month == 1:
    last_year=now.year-1
else:
    last_year=now.year

last="January February March April May June July August September Octobor November December".split()[last_month-1]
name = "Employee Target vs Achievement "+last+" " +str(last_year)+".xlsx"

# Read the excel sheet to pandas dataframe
df = pd.read_excel("one.xls", sheet_name=0,converters={"DIVISION":str,})
df.head(5)

,CLIENT,START_DATE,END_DATE,TERRITORY_CODE,EMPP_CODE,EMPP_NAME,DESIGNATION,HIERARCHY_LVL,DIVISION,NO_OF_INVOICES,...,NET_VALUE,GROSS_VALUE,PREVMONTH_CREDIT,CURRMONTH_CREDIT,PREVMONTH_DUE_COLLECTION,CURRMONTH_DUE_COL,TOTAL_DUE,CURR_MON_TOTAL_COL,TARGET_AMOUNT,TARGET_ACHV
0,300,01.11.2021,30.11.2021,AGM02-P,EM00000168,Mr. Bishawjit Kumar Shome,"AGM, Sales",9,01,180128,...,442699926,521171407,0,"16,187,178.54",0,"15,565,408.11",0,0,480711000,92.09
1,300,01.11.2021,30.11.2021,AGM01-P,EM00001086,Md. Shahjahan,"AGM, Sales",9,01,0,...,420730580,495415334,0,0.00,0,"14,669,334.73",0,0,499289000,84.27
2,300,01.11.2021,30.11.2021,SM002-P,EM00000351,Md. Sultan Mahamud Alam,SM,7,01,0,...,78022612,91847071,0,0.00,0,"1,864,134.39",0,0,82314000,94.79
3,300,01.11.2021,30.11.2021,DMS12-P,EM00000184,Mr. Salim Mahamod,DMS,6,01,0,...,47479827,56159266,0,0.00,0,"571,211.95",0,0,48129000,98.65
4,300,01.11.2021,30.11.2021,DMS10-P,EM00000359,Md. Wazed Ali,DMS,6,01,27712,...,59429291,69903481,0,"16,187,178.54",0,"991,075.94",0,0,67477000,88.07

# Hasib vai Employee Target vs Achievement

In [69]:
# Hasib vai Employee Target vs Achievement

hasib = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","HIERARCHY_LVL","DIVISION","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]
hasib.head(2)

writer = pd.ExcelWriter(str(name), engine='xlsxwriter') 
hasib.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

# Raw Master Data

In [70]:
df2 = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","DIVISION","HIERARCHY_LVL","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]

df2['TARGET_AMOUNT'] = df['TARGET_AMOUNT'].div(100000).round(decimals=2)
df2['NET_VALUE'] = df['NET_VALUE'].div(100000).round(decimals=2)
df2["TARGET_ACHV"] = df2["TARGET_ACHV"].round(3)

print("Total ZMIO with vacant Employe : "+ str(df2.shape[0]))

if 'Plant' not in df2.columns:
    df2.insert(2,'Plant',"")

df3 = df2[~df2.EMPP_CODE.str.contains("VAC")]


writer = pd.ExcelWriter("Master_Data.xlsx", engine='xlsxwriter') 
df3.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

print("Total ZMIO Without Employe : "+ str(df3.shape[0]))

df2.head(50)

c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

Total ZMIO with vacant Employe : 2781
Total ZMIO Without Employe : 2773

,EMPP_CODE,EMPP_NAME,Plant,TERRITORY_CODE,DIVISION,HIERARCHY_LVL,TARGET_AMOUNT,NET_VALUE,TARGET_ACHV
0,EM00000168,Mr. Bishawjit Kumar Shome,,AGM02-P,01,9,"4,807.11","4,427.00",92.09
1,EM00001086,Md. Shahjahan,,AGM01-P,01,9,"4,992.89","4,207.31",84.27
2,EM00000351,Md. Sultan Mahamud Alam,,SM002-P,01,7,823.14,780.23,94.79
3,EM00000184,Mr. Salim Mahamod,,DMS12-P,01,6,481.29,474.80,98.65
4,EM00000359,Md. Wazed Ali,,DMS10-P,01,6,674.77,594.29,88.07
5,EM00000539,Mr. Chandan Krishna Pandit,,DMS08-P,01,6,353.17,260.58,73.78
6,EM00000572,Md. Rabiul Hossen,,DMS09-P,01,6,"1,110.09","1,011.24",91.09
7,EM00000622,Mr. Khondoker Tariqul Islam,,DMS13-P,01,6,913.72,766.64,83.90
8,EM00001391,Md. Anwar Hossain,,DMS11-P,01,6,954.21,869.89,91.16
9,EM00002785,Mr. Syed Sakhawat Hossain,,DMS01-P,01,6,730.34,637.05,87.22
10,EM00010023,Md. Moniruzzaman,,DMS02-P,01,6,"1,020.77",857.96,84.05
11,EM00011146,Md. Safar Ali,,DMS03-P,01,6,898.34,672.75,74.89
12,EM00011148,Kazi Sazzad Hossain,,DMS05-P,01,6,593.85,495.36,83.41
13,EM00000402,Mr. Dipok Kumar Bhowmic,,KERSM1P,01,4,240.26,192.81,80.25
14,EM00000493,Md. Aminul Islam,,AMS10-P,01,4,235.81,195.49,82.90
15,EM00000546,Md. Delower Hossain,,AMS12-P,01,4,227.93,239.60,105.12
16,EM00000679,Mr. Minu Ahmed,,AMS11-P,01,4,358.04,299.86,83.75
17,EM00000693,Md. Masudur Rahman,,AMS17-P,01,4,246.89,209.21,84.74
18,EM00000694,Muhammad Zahidul Islam,,AMS21-P,01,4,226.37,206.29,91.13
19,EM00000773,Muhammad Rakib Hasan,,AMS16-P,01,4,186.68,172.58,92.45
20,EM00000834,Mohammad Rana Mean,,FARSM2P,01,4,202.30,180.48,89.21
21,EM00001027,Mohammad Asraful Islam,,AMS01-P,01,4,163.30,159.78,97.85
22,EM00001054,Md. Hamidur Rahman Sayed,,AMS15-P,01,4,232.76,222.82,95.73
23,EM00001093,Md. Sayed Enam Ahmed,,RARSM1P,01,4,313.70,250.35,79.80
24,EM00001110,Mr. Amal Kanti Das,,CORSM1P,01,4,239.59,215.31,89.86
25,EM00001139,Mr. Anis Howlader,,AMS18-P,01,4,82.93,79.67,96.07
26,EM00001295,Mr. Suman Kumar Sutra Dhar,,AMS19-P,01,4,226.61,218.10,96.24
27,EM00001321,Mohammad Kamal Hossain Mina,,FARSM1P,01,4,216.43,194.44,89.84
28,EM00001395,Md. Khurshid Jahan,,BORSM2P,01,4,182.63,117.06,64.10
29,EM00001485,Md. Humayunur Rashid,,AMS22-P,01,4,404.84,329.51,81.39
30,EM00001495,Md. Mustafizur Rahman,,PARSM4P,01,4,106.07,102.54,96.67
31,EM00001504,Md. Mizanur Rahman,,UTRSM1P,01,4,191.70,182.92,95.42
32,EM00001577,Muhammad Shakhawat Hossain,,AMS13-P,01,4,152.04,143.09,94.11
33,EM00001595,Md. Abdul Baki Bhuyan,,FERSM1P,01,4,272.94,230.86,84.58
34,EM00001758,Mr. Mizanur Rahman,,NORSM2P,01,4,224.64,182.99,81.46
35,EM00001759,Mr. Golam Mostofa,,BBRSM1P,01,4,329.92,294.50,89.26
36,EM00001761,Muhammad Azad Mia,,DHRSM1P,01,4,70.13,71.40,101.80
37,EM00002055,Mohammad Humyun Kabir,,SYRSM1P,01,4,194.88,178.71,91.70
38,EM00002110,Md. Zahid Hossain,,BARSM2P,01,4,199.60,157.26,78.79
39,EM00002176,Mr. Abdur Rahman Khan,,NARSM2P,01,4,230.76,204.36,88.56
40,EM00002252,Muhammad Jakir Hussain,,CURSM2P,01,4,194.04,204.87,105.58
41,EM00002497,Md. Abdullah-Al-Mamun,,NARSM1P,01,4,242.37,236.89,97.74
42,EM00002498,A.K.M. Nazmul Hasan,,CARSM1P,01,4,229.08,231.32,100.97
43,EM00002527,Mohammad Shwokat Ali Khan,,PARSM1P,01,4,73.96,73.44,99.29
44,EM00002548,Md. Abdul Karim,,MYRSM1P,01,4,146.75,112.82,76.88
45,EM00002638,Mr. Shah Kamruzzaman,,PBRSM1P,01,4,160.32,153.03,95.45
46,EM00002806,Mr. S. M. Shofiqul Islam,,KURSM1P,01,4,211.83,199.88,94.36
47,EM00003014,Mohammad Khorshed Alam,,AMS20-P,01,4,212.82,181.64,85.35
48,EM00004112,Mohammad Sadequr Rahman,,KIRSM1P,01,4,238.77,201.60,84.43
49,EM00011153,Md. Tariqul Islam,,BORSM1P,01,4,241.69,151.96,62.87

# Shafiq Boss Clossing Raw Data

In [71]:
# Shafiq Boss Data format


# df2 = df[["EMPP_CODE","EMPP_NAME","TERRITORY_CODE","DIVISION","HIERARCHY_LVL","TARGET_AMOUNT","NET_VALUE","TARGET_ACHV"]]

# df2['TARGET_AMOUNT'] = df['TARGET_AMOUNT'].div(100000).round(2)
# df2['NET_VALUE'] = df['TARGET_AMOUNT'].div(100000).round(2)

# print("Total ZMIO Employe : "+ str(df2.shape[0]))


division = ["01","02","04"]
Hieararchy = [2,3,4,5,6,7,8,9,10]

Boss_df = df3[df3.EMPP_CODE != "EM00702459"]

Boss_df2 = Boss_df[Boss_df['DIVISION'].isin(division) & Boss_df['HIERARCHY_LVL'].isin(Hieararchy)]


print("Total Row : " + str(Boss_df.shape[0]))

print("Total Mail count : " + str(Boss_df2.shape[0]))

Boss_df2["TARGET_ACHV"] = Boss_df2["TARGET_ACHV"].round(2)

writer = pd.ExcelWriter("Boss_Raw_Data.xlsx", engine='xlsxwriter') 
Boss_df2.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

Boss_df2.head(150)

Total Row : 2772
Total Mail count : 537

c:\users\aristo\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,EMPP_CODE,EMPP_NAME,Plant,TERRITORY_CODE,DIVISION,HIERARCHY_LVL,TARGET_AMOUNT,NET_VALUE,TARGET_ACHV
0,EM00000168,Mr. Bishawjit Kumar Shome,,AGM02-P,01,9,"4,807.11","4,427.00",92.09
1,EM00001086,Md. Shahjahan,,AGM01-P,01,9,"4,992.89","4,207.31",84.26
2,EM00000351,Md. Sultan Mahamud Alam,,SM002-P,01,7,823.14,780.23,94.79
3,EM00000184,Mr. Salim Mahamod,,DMS12-P,01,6,481.29,474.80,98.65
4,EM00000359,Md. Wazed Ali,,DMS10-P,01,6,674.77,594.29,88.07
...,...,...,...,...,...,...,...,...,...
145,EM00002561,Mr. Abul Basher,,FE070-P,01,2,37.10,37.46,100.95
146,EM00002563,Mohammad Al Amin Mounshe,,NO040-P,01,2,48.15,37.07,77.00
147,EM00002570,Md. Khairuzzaman,,JA040-P,01,2,33.80,23.56,69.70
148,EM00002573,Sk. Md. Lutfar Rahaman,,BA060-P,01,2,38.93,30.96,79.54
149,EM00002603,Mr. Mamun Choudhury,,CH030-P,01,2,31.65,28.46,89.92

# 100% AND 5 LAC 6 REPORTS

In [72]:
#1-PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT % FOR  AUG 2021

Pmio100ABOVE = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==1) &(df3["TARGET_ACHV"]>=100)]

# P100ABOVE.head(10)
print("PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  " + str(Pmio100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"pharma\PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Pmio100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------


#2-PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT % FOR AUG 2021
Pam100ABOVE = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==2) &(df3["TARGET_ACHV"]>=100)]

# Pam100ABOVE.head(10)
print("PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  " + str(Pam100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"pharma\PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Pam100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()


#----------------------------------------------------------------------------------------------------------


#3-Pharma 5 LAC AND ABOVE SALES MIO-SMIO AUG 2021

Pmio5above = df3[(df3["DIVISION"]=="01") & (df3["HIERARCHY_LVL"]==1) &(df3["NET_VALUE"]>=5)]

# Pmio5above.head(10)
print("Pharma 5 LAC AND ABOVE SALES MIO-SMIO  " + str(Pmio5above.shape[0]))

writer = pd.ExcelWriter(r"pharma\Pharma 5 LAC AND ABOVE SALES MIO-SMIO.xlsx", engine='xlsxwriter') 
Pmio5above.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------



#1-AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT % FOR  AUG 2021

Amio100ABOVE = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==1) &(df3["TARGET_ACHV"]>=100)]

# Amio100ABOVE.head(10)
print("AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  " + str(Amio100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"ag\AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Amio100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

#----------------------------------------------------------------------------------------------------------

#2-AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT % FOR AUG 2021

Aam100ABOVE = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==2) &(df3["TARGET_ACHV"]>=100)]

# Aam100ABOVE.head(10)
print("AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  " + str(Aam100ABOVE.shape[0]))

writer = pd.ExcelWriter(r"ag\AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT.xlsx", engine='xlsxwriter') 
Aam100ABOVE.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()
#----------------------------------------------------------------------------------------------------------


#3-AG 5 LAC AND ABOVE SALES MIO-SMIO AUG 2021

Amio5above = df3[(df3["DIVISION"]=="02") & (df3["HIERARCHY_LVL"]==1) &(df3["NET_VALUE"]>=5)]

# Amio5above.head(10)
print("AG 5 LAC AND ABOVE SALES MIO-SMIO  " + str(Amio5above.shape[0]))

writer = pd.ExcelWriter(r"ag\AG 5 LAC AND ABOVE SALES MIO-SMIO.xlsx", engine='xlsxwriter') 
Amio5above.to_excel(writer, sheet_name='Sheet1',index=False)
writer.save()

print("")


print("Total 100 % and above achiver (pharma+ag) : " + str(Pmio100ABOVE.shape[0]+Pam100ABOVE.shape[0]+Amio100ABOVE.shape[0]+Aam100ABOVE.shape[0]))

PHARMA MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  366
PHARMA AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  49
Pharma 5 LAC AND ABOVE SALES MIO-SMIO  882
AG MIO-SMIO WITH 100 AND ABOVE ACHIEVEMENT  49
AG AM-SAM WITH 100 AND ABOVE ACHIEVEMENT  3
AG 5 LAC AND ABOVE SALES MIO-SMIO  95

Total 100 % and above achiver (pharma+ag) : 467